#!/bin/bash

set -xe

cp /tmp/resources/entrypoint.sh /entrypoint.sh

#-------------------------------------------------------------------------------
# bulid dependencies
#-------------------------------------------------------------------------------
dpkg -l | awk '{print $2}' > /tmp/resources/pkg-list-pre.txt
apt-get update
apt-get --yes install \
  bc \
  build-essential \
  cmake \
  curl \
  diffutils \
  git \
  kmod \
  libcurl4-openssl-dev \
  wget

#-------------------------------------------------------------------------------
# build
#-------------------------------------------------------------------------------
export KERNELVER=$(uname -r  | cut -d '-' -f 1)
export KERNELDIR=/linux-$KERNELVER

cd /
curl -L -o linux-${KERNELVER}.tar.gz https://www.kernel.org/pub/linux/kernel/v4.x/linux-${KERNELVER}.tar.gz
tar zxf linux-${KERNELVER}.tar.gz
cd linux-${KERNELVER}
zcat /proc/1/root/proc/config.gz > .config
make modules_prepare
make headers_install INSTALL_HDR_PATH=/usr
mv .config ../config
cd ..
git clone https://github.com/draios/sysdig.git
cd sysdig
git checkout ${application_version}
mkdir build
cd build
cmake ..
KERNELDIR=/linux-$KERNELVER make driver -j $(nproc)
make curl -j $(nproc)
make jq -j $(nproc)
make b64 -j $(nproc)
make ncurses -j $(nproc)
make sysdig -j $(nproc)
make csysdig -j $(nproc)
strip userspace/sysdig/sysdig
strip userspace/sysdig/csysdig
make install
mv driver/sysdig-probe.ko \
   /usr/lib/modules-load.d/

#-------------------------------------------------------------------------------
# cleanup
#-------------------------------------------------------------------------------

# sources and builds
dpkg -l | awk '{print $2}' > /tmp/resources/pkg-list-post.txt
apt-get purge -y --force-yes $(diff \
    --unchanged-line-format= \
    --old-line-format= \
    --new-line-format='%L' \
    /tmp/resources/pkg-list-pre.txt \
    /tmp/resources/pkg-list-post.txt | \
    grep -v kmod | \
    xargs)
rm -Rf /linux-* /sysdig /var/lib/apt

exit 0
